# start from the last golang base image
FROM golang:latest

# Add Maintainer Info
LABEL maintainer ="Raveen <raveenseshan@live.com"

# Set the current workig directory inside the container
WORKDIR /apifile

# Copy Go Modules dependency requirements file
COPY go.md .

#Copy Go Modules expected hashes file
COPY go.sum .

# Download dependency
RUN go mod download

#Copy all the app sources (recursively cioies fules and directories from the host into the directori
COPY . .

#Set http port
ENV PORT 8080

#Build the app dependencies
RUN go build

# Remove source files
RUN find . -name "*.go" -type f -delete


# Make port 8080 avaiable to the world outside the container
EXPOSE $PORT

#Run the app dependencies
CMD ["./golang-gin-poc"]
